/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as MembersNewRouteImport } from './routes/members/new'
import { Route as MembersMemberIdIndexRouteImport } from './routes/members/$memberId/index'
import { Route as MembersMemberIdEditRouteImport } from './routes/members/$memberId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersNewRoute = MembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdIndexRoute = MembersMemberIdIndexRouteImport.update({
  id: '/members/$memberId/',
  path: '/members/$memberId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdEditRoute = MembersMemberIdEditRouteImport.update({
  id: '/members/$memberId/edit',
  path: '/members/$memberId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/members/new': typeof MembersNewRoute
  '/members/': typeof MembersIndexRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId/': typeof MembersMemberIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/members/new': typeof MembersNewRoute
  '/members': typeof MembersIndexRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId': typeof MembersMemberIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/members/new': typeof MembersNewRoute
  '/members/': typeof MembersIndexRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId/': typeof MembersMemberIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/members/new'
    | '/members/'
    | '/members/$memberId/edit'
    | '/members/$memberId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/members/new'
    | '/members'
    | '/members/$memberId/edit'
    | '/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/members/new'
    | '/members/'
    | '/members/$memberId/edit'
    | '/members/$memberId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MembersNewRoute: typeof MembersNewRoute
  MembersIndexRoute: typeof MembersIndexRoute
  MembersMemberIdEditRoute: typeof MembersMemberIdEditRoute
  MembersMemberIdIndexRoute: typeof MembersMemberIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/new': {
      id: '/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof MembersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId/': {
      id: '/members/$memberId/'
      path: '/members/$memberId'
      fullPath: '/members/$memberId/'
      preLoaderRoute: typeof MembersMemberIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId/edit': {
      id: '/members/$memberId/edit'
      path: '/members/$memberId/edit'
      fullPath: '/members/$memberId/edit'
      preLoaderRoute: typeof MembersMemberIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MembersNewRoute: MembersNewRoute,
  MembersIndexRoute: MembersIndexRoute,
  MembersMemberIdEditRoute: MembersMemberIdEditRoute,
  MembersMemberIdIndexRoute: MembersMemberIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
